FullStack/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views

from FullStackApp.views import CustomerRegistrationView

urlpatterns = [
                  path('', include('FullStackApp.urls')),
                  path('orders/payments/', include('payments.urls')),
                  re_path(r'^paypal/', include('paypal.standard.ipn.urls')),
                  path('admin/', admin.site.urls),
                  path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
                  path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
                  path('accounts/register/', CustomerRegistrationView.as_view(),
                       name='customer-register'),
                  path('accounts/password/change/',
                       auth_views.PasswordChangeView.as_view(template_name='registration/change_password.html'),
                       name='password_change'),
                  path('accounts/password/change/done/',
                       auth_views.PasswordChangeDoneView.as_view(),
                       name='password_change_done'),
                  path('accounts/password/reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

                  path('accounts/ reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
                       name='password_reset_confirm'),

                  path('accounts/password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(),
                       name='password_reset_complete'),
                  path('accounts/password/reset/done/', auth_views.PasswordResetDoneView.as_view(),
                       name='password_reset_done'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FullStackApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from FullStackApp.cart_views import cart_add, cart_remove, cart_update, cart_lists, cart_remove_all, cart_pre_checkout
from FullStackApp.views import Home, ProductDetail, CartViewList, Checkout, ListProductCategory, CartOrderSuccess, \
    check_out_auth_customer, ListOrders, OrderDetailView, view_that_asks_for_money

app_name = 'FullStackApp'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('product/categories/', ListProductCategory.as_view(), name='product-category'),
    path('product/<int:pk>/detail/', ProductDetail.as_view(), name='product-detail'),
    path('product/carts/', cart_lists, name='carts'),
    path('product/carts/order/success/', CartOrderSuccess.as_view(), name='cart_order_success'),
    path('product/checkout/', Checkout.as_view(), name='checkout'),
    path('product/pre-checkout/', cart_pre_checkout, name='pre-checkout'),
    path('product/<int:product_id>/carts/add/', cart_add, name='product-add'),
    path('product/<int:product_id>/carts/remove/', cart_remove, name='product-remove'),
    path('product/carts/clear/', cart_remove_all, name='product-remove-all'),
    path('product/carts/update/', cart_update, name='product-update'),
    path('product/carts/payment/', view_that_asks_for_money , name='product-payment'),
    path('product/checkout/auth/customer/', check_out_auth_customer, name='product-checkout-auth-customer'),
    path('orders/list/', ListOrders.as_view(), name='list-orders'),
    path('orders/<int:pk>/detail/', OrderDetailView.as_view(), name='order-detail'),


]

payments/urls.py
from django.urls import path

from payments import views

app_name = 'PaymentsApp'

urlpatterns = [
path('', views.HomePageView.as_view(), name='home'),
path('', views.PaymentFailure.as_view(), name='payment-failure'),
path('charge', views.charge, name='payment-charge'),
    ]

payments/models.py
from django.db import models

# Create your models here.

FullStackApp/views.py
from decimal import Decimal

from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.db import transaction
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView, ListView, DetailView, FormView, CreateView
from paypal.standard.forms import PayPalPaymentsForm

from FullStack.settings import PAYPAL_RECEIVER_EMAIL
from FullStackApp.cart import Cart
from FullStackApp.cart_order import CartOrder
from FullStackApp.decorators import customer_required
from FullStackApp.email import send_email_account_created, send_order_email
from FullStackApp.forms import CartAddProductForm, CustomerOrderForm, CustomerRegistrationForm
from FullStackApp.models import Product, ShoppingCart, Category, ProductCategory, User, Customer, Orders, OrderDetail, \
    Shipping


# Class that lists all the orders requested by the customer to the customer
@method_decorator([login_required, customer_required], name='dispatch')
class ListOrders(ListView):
    template_name = 'FullStackApp/orders.html'
    model = Orders
    context_object_name = 'orders'
    paginate_by = 10
    pass

    def get_queryset(self):
        qs = super().get_queryset()
        customer = Customer.objects.get(user = self.request.user)
        qs = qs.filter(customer=customer, has_paid=True)
        return qs


# Class that lists all the orders details requested by the customer to the customer
@method_decorator([login_required, customer_required], name='dispatch')
class OrderDetailView(DetailView):
    template_name = 'FullStackApp/order_details.html'
    model = Orders
    context_object_name = 'order_detail'

    def get_queryset(self):
        qs = super().get_queryset()
        customer = Customer.objects.get(user=self.request.user)
        qs = qs.filter(customer=customer)
        return qs
    pass


# class ListOrderDetails(ListView):
#     template_name = 'FullStackApp/order_details.html'
#     model = OrderDetail
#     context_object_name = 'order_details'


# Class that lists all the Product available in the database
class ListProduct(ListView):
    template_name = 'FullStackApp/index.html'
    model = Product
    context_object_name = 'products'
    paginate_by = 9

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.order_by('id')

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data()
        product_form = CartAddProductForm()
        context_data['product_form'] = product_form
        return context_data


# Class that lists all the Product Category available in the database
class ListProductCategory(ListProduct):
    template_name = 'FullStackApp/categories.html'
    current_category = 'All'

    def get_queryset(self):
        qs = super().get_queryset()
        if 'categories' in self.request.GET:
            categories = self.request.GET.get('categories')
            print(categories)
            category = Category.objects.filter(name=categories)
            # product_category_id = ProductCategory.objects.filter(category=category)
            # Product.objects.filter(related_product__category=)
            if category:
                category = category[0]
                qs = qs.filter(related_product__category=category)
                self.current_category = categories
                self.paginate_by = None
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data()
        context_data['categories'] = Category.objects.all()
        context_data['current_category'] = self.current_category

        return context_data


# Class that shows each Product details available in the database
class ProductDetail(DetailView):
    template_name = 'FullStackApp/product.html'
    model = Product
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data()
        product_form = CartAddProductForm()
        context_data['product_form'] = product_form
        return context_data


class Home(View):
    def get(self, request, *args, **kwargs):
        view = ListProduct.as_view()
        return view(request, *args, **kwargs)


class ListCart(ListView):
    template_name = 'FullStackApp/cart.html'
    model = ShoppingCart
    context_object_name = 'carts'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(buy_now=True)
        return qs


# @method_decorator([login_required, ], name='dispatch')
class CartViewList(View):
    def get(self, request, *args, **kwargs):
        view = ListCart.as_view()
        return view(request, *args, **kwargs)

    pass

# Order Success page Class
class CartOrderSuccess(TemplateView):
    template_name = 'FullStackApp/cart_success.html'


class CustomerRegistrationView(CreateView):
    template_name = 'registration/register.html'
    form_class = CustomerRegistrationForm
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        username = form.cleaned_data['username']
        send_email_account_created(email, username, password, self.request)
        response = super().form_valid(form)
        return response


# Checkout View Class
class Checkout(FormView):
    template_name = 'FullStackApp/checkout.html'
    form_class = CustomerOrderForm
    cart_shipping_fee = 0
    total_cart_plus_shipping = 0
    success_url = reverse_lazy('PaymentsApp:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # shipping = None
        if 'cart_shipping_id' in self.request.session:
            shipping_id = self.request.session['cart_shipping_id']
            shipping = Shipping.objects.get(id=shipping_id)
            self.cart_shipping_fee = Decimal(shipping.shipping_cost)

        cart = Cart(self.request)
        if cart.get_total_price():
            self.total_cart_plus_shipping = cart.get_total_price() + self.cart_shipping_fee

        
        context['total_cart_plus_shipping'] = self.total_cart_plus_shipping
        context['cart_shipping_fee'] = self.cart_shipping_fee
        return context

    @transaction.atomic
    def form_valid(self, form):
        cart = Cart(self.request)
        shipping = None
        if 'cart_shipping_id' in self.request.session:
            shipping_id = self.request.session['cart_shipping_id']
            shipping = Shipping.objects.get(id=shipping_id)
            self.cart_shipping_fee = Decimal(shipping.shipping_cost)

        if cart.get_total_price():
            self.total_cart_plus_shipping = cart.get_total_price() + self.cart_shipping_fee

        if not cart or not shipping:
            return redirect('FullStackApp:carts')
        print(form.cleaned_data)
        create_account = form.cleaned_data['create_account']
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        company = form.cleaned_data['company']
        shipping_region = country = form.cleaned_data['country']
        address = form.cleaned_data['address']
        address_2 = form.cleaned_data['address_2']
        zipcode = form.cleaned_data['zipcode']
        city = form.cleaned_data['city']
        phone_number = form.cleaned_data['phone_number']
        username = email = form.cleaned_data['email']
        order_cart = CartOrder()
        order = order_cart.create_order(total_amount=self.total_cart_plus_shipping, shipping=shipping)

        print('order', order)
        cart_list = []
        for item in cart:
            product = item['product']
            size = product.get_default_size()
            color = product.get_default_colour()
            attributes = 'size: {}\n'.format(size)
            attributes += 'color: {}'.format(color)
            cart_list.append({
                'order':order,
                'product':product,
                'attributes': attributes,
                'product_name':product.name,
                'unit_cost':item['price'],
                'quantity':item['quantity'],
            })
        print('car_list', cart_list)
        order_detail = OrderDetail.objects.bulk_create(
            [OrderDetail(**q) for q in cart_list]
        )

        print('order detail', order_detail)
        # //send email to customer on order
        # send_order_email(email, order.tracking_id, self.request)
        print(create_account)
        if create_account:
            password = User.objects.make_random_password()
            # hash_password = make_password(password)
            user = User(first_name=first_name, last_name=last_name,
                        email=email, username=email, phone_number=phone_number,
                        is_customer=True)
            user.set_password(password)
            user.save()
            print('user', user)
            # //send email to customer
            customer = Customer.objects.create(user=user, company=company,
                                address_1=address, address_2=address_2,
                                city=city, region='Europe',
                                postal_code=zipcode, country='America',
                                shipping_region=shipping_region,
                                day_phone=phone_number)
            order.customer = customer
            print('customer', customer)
            send_email_account_created(email, email, password, self.request)
            order.save()

        response = super().form_valid(form)
        self.request.session['cart_order_id'] = int(order.id)
        cart.clear()
        return response

payments/views.py
import stripe
from django.shortcuts import render, redirect

# Create your views here.


# payments/views.py
from django.views.decorators.http import require_POST
from django.views.generic.base import TemplateView

from FullStack import settings
from FullStackApp.cart import Cart
from FullStackApp.email import send_order_email
from FullStackApp.models import Orders

stripe.api_key = settings.STRIPE_SECRET_KEY # new


class HomePageView(TemplateView):
    template_name = 'payments/home.html'

    def get(self, request, *args, **kwargs):
        if 'cart_order_id' not in self.request.session:
           return redirect('FullStackApp:carts')

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):  # new
        context = super().get_context_data(**kwargs)
        context['key'] = settings.STRIPE_PUBLISHABLE_KEY
        if 'cart_order_id' in self.request.session:
            cart_order_id = self.request.session['cart_order_id']
            order = Orders.objects.get(id=cart_order_id)
            print('payments order: ', order)
            context['total_amount'] = order.total_amount
            context['stripe_amount'] = order.total_amount *100
        print(context)
        return context


@require_POST
def charge(request):
    if request.method == 'POST':
        data = request.POST
        print(data)
        order = None
        if 'cart_order_id' in request.session:
            cart_order_id = request.session['cart_order_id']
            order = Orders.objects.get(id=cart_order_id)
            del request.session['cart_order_id']

        if order is None:
            return redirect('PaymentsApp:payment-failure')

        description = 'Products Payment Amount of $ {}'.format(order.total_amount)
        charge = stripe.Charge.create(
            amount=round(order.total_amount*100),
            currency='usd',
            description=description,
            source=request.POST['stripeToken']
        )

        cart = Cart(request)
        order.has_paid = True
        order.save()
        send_order_email(order.customer.user.email, order.tracking_id, request)
        cart.clear()
        return render(request, 'FullStackApp/cart_success.html')


class PaymentFailure(TemplateView):
    template_name = 'payments/Failure.html'

FullStackApp/templates/FullStackApp/categories.html
{% extends 'FullStackApp/base.html' %}
{% load static %}
{% block linked_style %}

    <link rel="stylesheet" type="text/css"
          href="{% static 'FullStackApp/plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'FullStackApp/plugins/OwlCarousel2-2.2.1/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'FullStackApp/styles/categories.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'FullStackApp/styles/categories_responsive.css' %}">
{% endblock %}

{% block linked_script %}
    <script src="{% static 'FullStackApp/js/categories.js' %}"></script>
{% endblock %}

{% block content %}
    <!-- Home -->

    <div class="home">
        <div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="{% static 'FullStackApp/images/categories.jpg' %}"
             data-speed="0.8"></div>
        <div class="home_container">
            <div class="home_content">
                <div class="home_title">Shop</div>
                <div class="breadcrumbs">
                    <ul class="d-flex flex-row align-items-center justify-content-start">
                        <li><a href="{% url 'FullStackApp:home' %}">Home</a></li>
                        <li><a href="{% url 'FullStackApp:product-category' %}">Categories</a></li>
                        <li>{{current_category }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- Products -->

    <div class="products">

        <!-- Sorting & Filtering -->
        <div class="products_bar">
            <div class="section_container">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="products_bar_content d-flex flex-column flex-xxl-row align-items-start align-items-xxl-center justify-content-start">
                                <div class="product_categories">
                                    <ul class="d-flex flex-row align-items-start justify-content-start flex-wrap">
                                        <li class="active"><a href="#">All</a></li>

                                        <li><a href="#">Hot Products</a></li>
                                        <li><a href="#">New Products</a></li>
                                        <li><a href="#">Sale Products</a></li>
                                    </ul>
                                </div>
                                <div class="products_bar_side ml-xxl-auto d-flex flex-row align-items-center justify-content-start">
                                    <div class="products_dropdown product_dropdown_sorting">
                                        <div class="isotope_sorting_text"><span>Default Sorting</span><i
                                                class="fa fa-caret-down" aria-hidden="true"></i></div>
                                        <ul>
                                            <li class="item_sorting_btn"
                                                data-isotope-option='{ "sortBy": "original-order" }'>Default
                                            </li>
                                            <li class="item_sorting_btn" data-isotope-option='{ "sortBy": "price" }'>
                                                Price
                                            </li>
                                            <li class="item_sorting_btn" data-isotope-option='{ "sortBy": "name" }'>
                                                Name
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="product_view d-flex flex-row align-items-center justify-content-start">
                                        <div class="view_item active"><img src="{% static 'FullStackApp/images/view_1.png' %}" alt=""></div>
                                        <div class="view_item"><img src="{% static 'FullStackApp/images/view_2.png' %}" alt=""></div>
                                        <div class="view_item"><img src="{% static 'FullStackApp/images/view_3.png' %}" alt=""></div>
                                    </div>
                                    <div class="products_dropdown text-right product_dropdown_filter">
                                        <div class="isotope_filter_text"><span>Filter</span><i class="fa fa-caret-down"
                                                                                               aria-hidden="true"></i>
                                        </div>
                                        <ul>

                                            <li class="item_filter_btn" data-filter="*">All</li>
                                            {% for category in categories %}
                                                <li class="item_filter_btn" data-filter=".{{category.name}}">{{category.name}}</li>
                                            {% endfor %}
{#                                            <li class="item_filter_btn" data-filter=".hot">Hot</li>#}
{#                                            <li class="item_filter_btn" data-filter=".new">New</li>#}
{#                                            <li class="item_filter_btn" data-filter=".sale">Sale</li>#}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="section_container">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="products_container grid">

                            {% for product in products %}
                                <!-- Product -->
                                <div class="product grid-item {{ product.get_categories_string }}">
                                    <div class="product_inner">
                                        <div class="product_image">
                                            <img src="{{ product.image.url }}" alt="" width="510px">
                                            <div class="product_tag">hot</div>
                                        </div>
                                        <div class="product_content text-center">
                                            <div class="product_title"><a href="{% url 'FullStackApp:product-detail' product.pk %}">{{ product.name }}</a>
                                            </div>
                                            <div class="product_price">${{ product.price }}</div>
{#                                            <div class="product_button ml-auto mr-auto trans_200"><a href="{% url 'FullStackApp:product-add' product.id %}">add to#}
{#                                                cart</a></div>#}
                                            <form action="{% url 'FullStackApp:product-add' product.pk %}"
                                                  method="post">
                                                {% csrf_token %}

                                                {{ product_form.update }}
                                                {{ product_form.quantity }}
                                                <button type="submit"
                                                        class="btn product_button ml-auto mr-auto trans_200">
                                                    add to cart
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </div>

                            {% endfor %}

                        </div>
                    <section>

                                {% if is_paginated %}
                                    <p class="text-success">
                                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                    </p>
                                    <ul class="pagination">
                                        {% if page_obj.has_previous %}
                                            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                                        {% else %}
                                            <li class="disabled"><span>&laquo;</span></li>
                                        {% endif %}
                                        {% for i in paginator.page_range %}
                                            {% if page_obj.number == i %}
                                                <li><a class="active" href="#">{{ i }}</a> <span
                                                        class="sr-only">(current)</span></li>
                                            {% else %}
                                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if page_obj.has_next %}
                                            <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                                        {% else %}
                                            <li class="disabled"><span>&raquo;</span></li>
                                        {% endif %}
                                    </ul>
                                {% endif %}

                            </section>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

FullStackApp/templates/FullStackApp/orders.html
{% extends 'FullStackApp/base.html' %}
{% load static %}
{% block linked_style %}


    <link rel="stylesheet" type="text/css" href="{% static 'FullStackApp/styles/cart.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'FullStackApp/styles/cart_responsive.css' %}">
{% endblock %}

{% block linked_script %}
     <script src="{% static 'FullStackApp/js/cart.js' %}"></script>
{% endblock %}
{% block content %}

     <div class="home">
        <div class="parallax_background parallax-window" data-parallax="scroll"
             data-image-src="{% static 'FullStackApp/images/product_background.jpg' %}" data-speed="0.8"></div>
        <div class="home_container">
            <div class="home_content">
                <div class="home_title">Cart</div>
                <div class="breadcrumbs">
                    <ul class="d-flex flex-row align-items-center justify-content-start">
                        <li><a href="{% url 'FullStackApp:home' %}">Home</a></li>
                        <li>Your ORDERS</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
 <div id="portlet2" class="panel-collapse  in">
                    <div class="portlet-body">
                        <div class="table-responsive">
                            <table id="example" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Tracking Id</th>
                                    <th>Total Amount</th>
                                    <th>Created On</th>
                                    <th>Shipped on</th>
                                    <th>Status</th>
                                    <th>Comments</th>
                                    <th>Reference</th>
                                    <th>Shipping</th>
                                    <th>Tax</th>
                                </tr>
                                </thead>
                                <tbody>

                                {% if orders %}
                                    {% for order in orders %}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td>
                                                <a href="{% url 'FullStackApp:order-detail' order.pk %}">{{ order.tracking_id }}</a>
                                                </td>
                                            <td>${{ order.total_amount }}</td>
                                            <td> {{ order.created_on}}</td>
                                            <td> {{ order.shipped_on }}</td>
                                            <td> {{ order.status }}</td>
                                            <td>{{ order.comments }}</td>
                                            <td>{{ order.reference }}</td>
                                            <td>{{ order.shipping }}</td>
                                            <td>${{ order.tax }}</td>
{#                                            <td>#}
{#                                                <a class="btn btn-primary" type="button" data-toggle="modal"#}
{#                                                   href="#">#}
{#                                                    <i class="fa fa-trash"> </i>#}
{#                                                </a>#}
{#                                            </td>#}

                                        </tr>
                                    {% endfor %}
                                {% endif %}

                                </tbody>
                            </table>
                        </div>
                    </div>

                    <section>

                {% if is_paginated %}
                    <p class="text-success">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </p>
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                            <li class="disabled"><span>&laquo;</span></li>
                        {% endif %}
                        {% for i in paginator.page_range %}
                            {% if page_obj.number == i %}
                                <li><a class="active" href="#">{{ i }}</a> <span
                                        class="sr-only">(current)</span></li>
                            {% else %}
                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                        {% else %}
                            <li class="disabled"><span>&raquo;</span></li>
                        {% endif %}
                    </ul>
                {% endif %}

            </section>
                <br>
                </div>

{% endblock %}