FullStack/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views

from FullStackApp.views import CustomerRegistrationView

urlpatterns = [
                  path('', include('FullStackApp.urls')),
                  path('orders/payments/', include('payments.urls')),
                  re_path(r'^paypal/', include('paypal.standard.ipn.urls')),
                  path('admin/', admin.site.urls),
                  path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
                  path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
                  path('accounts/register/', CustomerRegistrationView.as_view(),
                       name='customer-register'),
                  path('accounts/password/change/',
                       auth_views.PasswordChangeView.as_view(template_name='registration/change_password.html'),
                       name='password_change'),
                  path('accounts/password/change/done/',
                       auth_views.PasswordChangeDoneView.as_view(),
                       name='password_change_done'),
                  path('accounts/password/reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

                  path('accounts/ reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
                       name='password_reset_confirm'),

                  path('accounts/password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(),
                       name='password_reset_complete'),
                  path('accounts/password/reset/done/', auth_views.PasswordResetDoneView.as_view(),
                       name='password_reset_done'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FullStackApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from FullStackApp.cart_views import cart_add, cart_remove, cart_update, cart_lists, cart_remove_all, cart_pre_checkout
from FullStackApp.views import Home, ProductDetail, CartViewList, Checkout, ListProductCategory, CartOrderSuccess, \
    check_out_auth_customer, ListOrders, OrderDetailView, view_that_asks_for_money

app_name = 'FullStackApp'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('product/categories/', ListProductCategory.as_view(), name='product-category'),
    path('product/<int:pk>/detail/', ProductDetail.as_view(), name='product-detail'),
    path('product/carts/', cart_lists, name='carts'),
    path('product/carts/order/success/', CartOrderSuccess.as_view(), name='cart_order_success'),
    path('product/checkout/', Checkout.as_view(), name='checkout'),
    path('product/pre-checkout/', cart_pre_checkout, name='pre-checkout'),
    path('product/<int:product_id>/carts/add/', cart_add, name='product-add'),
    path('product/<int:product_id>/carts/remove/', cart_remove, name='product-remove'),
    path('product/carts/clear/', cart_remove_all, name='product-remove-all'),
    path('product/carts/update/', cart_update, name='product-update'),
    path('product/carts/payment/', view_that_asks_for_money , name='product-payment'),
    path('product/checkout/auth/customer/', check_out_auth_customer, name='product-checkout-auth-customer'),
    path('orders/list/', ListOrders.as_view(), name='list-orders'),
    path('orders/<int:pk>/detail/', OrderDetailView.as_view(), name='order-detail'),


]

payments/urls.py
from django.urls import path

from payments import views

app_name = 'PaymentsApp'

urlpatterns = [
path('', views.HomePageView.as_view(), name='home'),
path('', views.PaymentFailure.as_view(), name='payment-failure'),
path('charge', views.charge, name='payment-charge'),
    ]

payments/models.py
from django.db import models

# Create your models here.

payments/views.py
import stripe
from django.shortcuts import render, redirect

# Create your views here.


# payments/views.py
from django.views.decorators.http import require_POST
from django.views.generic.base import TemplateView

from FullStack import settings
from FullStackApp.cart import Cart
from FullStackApp.email import send_order_email
from FullStackApp.models import Orders

stripe.api_key = settings.STRIPE_SECRET_KEY # new


class HomePageView(TemplateView):
    template_name = 'payments/home.html'

    def get(self, request, *args, **kwargs):
        if 'cart_order_id' not in self.request.session:
           return redirect('FullStackApp:carts')

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):  # new
        context = super().get_context_data(**kwargs)
        context['key'] = settings.STRIPE_PUBLISHABLE_KEY
        if 'cart_order_id' in self.request.session:
            cart_order_id = self.request.session['cart_order_id']
            order = Orders.objects.get(id=cart_order_id)
            print('payments order: ', order)
            context['total_amount'] = order.total_amount
            context['stripe_amount'] = order.total_amount *100
        print(context)
        return context


@require_POST
def charge(request):
    if request.method == 'POST':
        data = request.POST
        print(data)
        order = None
        if 'cart_order_id' in request.session:
            cart_order_id = request.session['cart_order_id']
            order = Orders.objects.get(id=cart_order_id)
            del request.session['cart_order_id']

        if order is None:
            return redirect('PaymentsApp:payment-failure')

        description = 'Products Payment Amount of $ {}'.format(order.total_amount)
        charge = stripe.Charge.create(
            amount=round(order.total_amount*100),
            currency='usd',
            description=description,
            source=request.POST['stripeToken']
        )

        cart = Cart(request)
        order.has_paid = True
        order.save()
        send_order_email(order.customer.user.email, order.tracking_id, request)
        cart.clear()
        return render(request, 'FullStackApp/cart_success.html')


class PaymentFailure(TemplateView):
    template_name = 'payments/Failure.html'

payments/templates/payments/Failure.html
{% extends 'FullStackApp/base.html' %}
{% load static %}
{% block linked_style %}


    <link rel="stylesheet" type="text/css" href="{% static 'FullStackApp/styles/cart.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'FullStackApp/styles/cart_responsive.css' %}">
{% endblock %}

{% block linked_script %}
    <script src="{% static 'FullStackApp/js/cart.js' %}"></script>
{% endblock %}

{% block content %}

    <div class="home">
        <div class="parallax_background parallax-window" data-parallax="scroll"
             data-image-src="{% static 'FullStackApp/images/product_background.jpg' %}" data-speed="0.8"></div>
        <div class="home_container">
            <div class="home_content">
                <div class="home_title">Cart</div>
                <div class="breadcrumbs">
                    <ul class="d-flex flex-row align-items-center justify-content-start">
                        <li><a href="{% url 'FullStackApp:home' %}">Home</a></li>
                        <li>Your Cart</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- Cart -->

    <div class="cart_section">
        <h3 class="text-center">Your Payments</h3>
        <!-- writes out the form tag automatically -->
        <div class="text-center">
            <p>Sorry Your Payments could not be completed</p>
</div>
     </div>

{% endblock %}

payments/templates/payments/home.html
{% extends 'FullStackApp/base.html' %}
{% load static %}
{% block linked_style %}


    <link rel="stylesheet" type="text/css" href="{% static 'FullStackApp/styles/cart.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'FullStackApp/styles/cart_responsive.css' %}">
{% endblock %}

{% block linked_script %}
    <script src="{% static 'FullStackApp/js/cart.js' %}"></script>
{% endblock %}

{% block content %}

    <div class="home">
        <div class="parallax_background parallax-window" data-parallax="scroll"
             data-image-src="{% static 'FullStackApp/images/product_background.jpg' %}" data-speed="0.8"></div>
        <div class="home_container">
            <div class="home_content">
                <div class="home_title">Cart</div>
                <div class="breadcrumbs">
                    <ul class="d-flex flex-row align-items-center justify-content-start">
                        <li><a href="{% url 'FullStackApp:home' %}">Home</a></li>
                        <li>Your Cart</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- Cart -->

    <div class="cart_section">
        <h3 class="text-center">You will now be redirected to make Payments for your Order</h3>
        <p class="text-center">Please do not leave the page until you have made payments so your order can be completed</p>
        <!-- writes out the form tag automatically -->
        <div class="text-center">
            <form action="{% url 'PaymentsApp:payment-charge' %}" method="POST">
                {% csrf_token %}
                <script
                        src="https://checkout.stripe.com/checkout.js"
                        class="stripe-button"
                        data-description="Products Payment Amount of ${{ total_amount }}"
                        data-key="{{ key }}"
                        {#    data-image="/square-image.png"#}
                        data-name="TShopShirt Payment Gateway"
                        {#    data-description="2 widgets ($20.00)"#}
                        data-amount= {{ stripe_amount }}
                        data-locale="auto">
                </script>
            </form>

            {#    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"#}
            {#    data-key="{{ key }}"#}
            {#    data-description="Products Payment Amount of ${{ total_amount }}"#}
            {#    data-amount="{{ total_amount }}"#}
            {#    data-locale="auto">#}
            {#    </script>#}
        </div>
    </div>

{% endblock %}